name: DeepLinkTrigger
options:
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  bundleIdPrefix: com.deeplinkTrigger
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.0.0
settings:
  base:
    SWIFT_VERSION: "5.9"
targets:
  DeepLinkTrigger:
    type: application
    platform: macOS
    sources:
      - DeepLinkTrigger
    dependencies:
      - package: Sparkle
    settings:
      base:
        INFOPLIST_FILE: DeepLinkTrigger/Info.plist
        CODE_SIGN_ENTITLEMENTS: DeepLinkTrigger/DeepLinkTrigger.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.deeplinkTrigger.DeepLinkTrigger
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Linktor
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "1.1.0"
